config/routes.rb
Rails.application.routes.draw do
  get "users/show"
  get "event_attendances/create"
  get "event_attendances/destroy"
  get "events/index"
  get "events/new"
  get "events/create"
  get "events/show"
  get "events/edit"
  get "events/update"
  get "events/destroy"
  
  devise_for :users
  root "events#index"

  resources :events
  resources :users, only: [:show]

  post "/event_attendances", to: "event_attendances#create"
  delete "/event_attendances", to: "event_attendances#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'

  has_many :event_attendances, foreign_key: :attended_event_id, dependent: :destroy
  has_many :attendees, through: :event_attendances, source: :attendee

  has_many :invitations
  has_many :invited_users, through: :invitations, source: :user

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date >= ?', Time.now) }
  
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
    belongs_to :attendee, class_name: 'User'
    belongs_to :attended_event, class_name: 'Event'
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :event
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'

  has_many :event_attendances, foreign_key: :attendee_id, dependent: :destroy
  has_many :attended_events, through: :event_attendances, source: :attended_event

  has_many :invitations
  has_many :invited_events, through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/event_attendances_controller.rb
class EventAttendancesController < ApplicationController
  before_action :authenticate_user!

  def create
    EventAttendance.create(attendee_id: current_user.id, attended_event_id: params[:attended_event_id])
    redirect_to event_path(params[:attended_event_id])
  end

  def destroy
    attendance = EventAttendance.find_by(attendee_id: current_user.id, attended_event_id: params[:attended_event_id])
    attendance.destroy if attendance
    redirect_to event_path(params[:attended_event_id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]

  def index
    @past_events = Event.past.where(private: false)
    @upcoming_events = Event.upcoming.where(private: false)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)
    if @event.save
      redirect_to @event , notice: "Event created successfully."
    else
      render :new
    end
  end

  def show
    if @event.private && !@event.invited_users.include?(current_user) && @event.creator != current_user
      redirect_to root_path, alert: "You are not invited to this event."
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to @event
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to root_path, notice: "Event deleted."
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :date, :private, :description, invited_user_ids: [])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def authorize_user!
    redirect_to root_path, alert: "Not authorized" unless @event.creator == current_user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendances_helper.rb
module EventAttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/event_attendances/create.html.erb
<h1>EventAttendances#create</h1>
<p>Find me in app/views/event_attendances/create.html.erb</p>

app/views/event_attendances/destroy.html.erb
<h1>EventAttendances#destroy</h1>
<p>Find me in app/views/event_attendances/destroy.html.erb</p>

app/views/events/_form.html.erb
<%= form_with model: @event do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :location %>
  <%= f.text_field :location %><br>

  <%= f.label :date %>
  <%= f.datetime_select :date %><br>

  <%= f.label :private %>
  <%= f.check_box :private %><br>

  <% if User.count > 1 %>
    <%= f.label "Invite Users" %><br>
    <%= f.collection_select :invited_user_ids, User.where.not(id: current_user.id), :id, :email, {}, { multiple: true } %>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/events/create.html.erb
<h1>Events#create</h1>
<p>Find me in app/views/events/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Events#destroy</h1>
<p>Find me in app/views/events/destroy.html.erb</p>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= form_with model: @event, local: true do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>

  <div>
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>

  <div>
    <%= f.label :private, "Private Event?" %><br>
    <%= f.check_box :private %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <% if User.count > 1 %>
    <div>
      <%= f.label "Invite Users" %><br>
      <%= f.collection_select :invited_user_ids, User.where.not(id: current_user.id), :id, :email, { selected: @event.invited_user_ids }, { multiple: true } %>
    </div>
  <% end %>

  <div>
    <%= f.submit "Update Event" %>
  </div>
<% end %>

<%= link_to 'Back to Event', event_path(@event) %>

app/views/events/index.html.erb
<h1>Upcoming Events</h1>
<% @upcoming_events.each do |event| %>
  <%= link_to event.title, event_path(event) %> - <%= event.date %><br>
<% end %>

<h1>Past Events</h1>
<% @past_events.each do |event| %>
  <%= link_to event.title, event_path(event) %> - <%= event.date %><br>
<% end %>

<%= link_to "New Event", new_event_path if user_signed_in? %>

app/views/events/new.html.erb
<h1>Create a New Event</h1>

<%= form_with model: @event, local: true do |f| %>
  <div>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>

  <div>
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>

  <div>
    <%= f.label :private, "Private Event?" %><br>
    <%= f.check_box :private %>
  </div>

  <div>
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>

  <% if User.count > 1 %>
    <div>
      <%= f.label "Invite Users" %><br>
      <%= f.collection_select :invited_user_ids, User.where.not(id: current_user.id), :id, :email, {}, { multiple: true } %>
    </div>
  <% end %>

  <div>
    <%= f.submit "Create Event" %>
  </div>
<% end %>

<%= link_to 'Back to Events', events_path %>

app/views/events/show.html.erb
<h1><%= @event.title %></h1>
<p><%= @event.location %> at <%= @event.date %></p>

<p><strong>Description:</strong></p>
<p><%= @event.description %></p>

<% if user_signed_in? %>
  <% if current_user == @event.creator %>
    <%= link_to "Edit", edit_event_path(@event) %> |
    <%= link_to "Delete", event_path(@event), method: :delete, data: { confirm: "Are you sure?" } %>
  <% elsif !@event.attendees.include?(current_user) %>
    <%= button_to "Attend", event_attendances_path(attended_event_id: @event.id), method: :post %>
  <% else %>
    <%= button_to "Unattend", event_attendances_path(attended_event_id: @event.id), method: :delete %>
  <% end %>
<% end %>

<h2>Attendees:</h2>
<ul>
  <% @event.attendees.each do |attendee| %>
    <li><%= attendee.email %></li>
  <% end %>
</ul>

app/views/events/update.html.erb
<h1>Events#update</h1>
<p>Find me in app/views/events/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to "All Events", events_path %> |
        <%= link_to "My Profile", user_path(current_user) %> |
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to 'Sign In', new_user_session_path %> |
        <%= link_to 'Sign Up', new_user_registration_path %>
      <% end %>
    </nav>

    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1><%= @user.email %>'s Profile</h1>

<h2>Upcoming Events Created</h2>
<ul>
  <% @user.created_events.select { |e| e.date && e.date >= Time.now }.each do |event| %>
    <li><%= link_to event.title, event_path(event) %> - <%= event.date.strftime("%B %d, %Y %l:%M %p") %></li>
  <% end %>
</ul>

<h2>Past Events Created</h2>
<ul>
  <% @user.created_events.select { |e| e.date && e.date < Time.now }.each do |event| %>
    <li><%= link_to event.title, event_path(event) %> - <%= event.date.strftime("%B %d, %Y %l:%M %p") %></li>
  <% end %>
</ul>